
# Users

blake = User.create(username: "blaksedlacek" , password:"hunter1")
julie = User.create(username: "juliesedlacek" , password: "tjmax")
courtney = User.create(username: "courtneysedlacek" , password:"NYClivin")
matthew = User.create(username: "matthewsedlacek" , password:"tennis4life")
brian = User.create(username:"briansedlacek" , password:"emmy<3")
michael = User.create(username:"michaelsedlacek" , password: "gocougs!")


#Companies

mmm = Company.create(ticker: "MMM", name: "3M Company", logo: "https://logo.clearbit.com/3M.com", sector: "Industrials")
abt = Company.create(ticker: "ABT", name: "Abbott Laboratories", logo: "https://logo.clearbit.com/Abbott.com", sector: "Health Care")
abbv = Company.create(ticker: "ABBV", name: "AbbVie Inc.", logo: "https://logo.clearbit.com/AbbVie.com", sector: "Health Care")
abmd = Company.create(ticker: "ABMD", name: "ABIOMED Inc", logo: "https://logo.clearbit.com/ABIOMED.com", sector: "Health Care")
acn = Company.create(ticker: "ACN", name: "Accenture plc", logo: "https://logo.clearbit.com/Accenture.com", sector: "Information Technology")
atvi = Company.create(ticker: "ATVI", name: "Activision Blizzard", logo: "https://logo.clearbit.com/Activision.com", sector: "Communication Services")
adbe = Company.create(ticker: "ADBE", name: "Adobe Inc.", logo: "https://logo.clearbit.com/Adobe.com", sector: "Information Technology")
amd = Company.create(ticker: "AMD", name: "Advanced Micro Devices Inc", logo: "https://logo.clearbit.com/Advanced.com", sector: "Information Technology")
aap = Company.create(ticker: "AAP", name: "Advance Auto Parts", logo: "https://logo.clearbit.com/Advance.com", sector: "Consumer Discretionary")
aes = Company.create(ticker: "AES", name: "AES Corp", logo: "https://logo.clearbit.com/AES.com", sector: "Utilities")
afl = Company.create(ticker: "AFL", name: "AFLAC Inc", logo: "https://logo.clearbit.com/AFLAC.com", sector: "Financials")
a = Company.create(ticker: "A", name: "Agilent Technologies Inc", logo: "https://logo.clearbit.com/Agilent.com", sector: "Health Care")
apd = Company.create(ticker: "APD", name: "Air Products & Chemicals Inc", logo: "https://logo.clearbit.com/Air.com", sector: "Materials")
akam = Company.create(ticker: "AKAM", name: "Akamai Technologies Inc", logo: "https://logo.clearbit.com/Akamai.com", sector: "Information Technology")
alk = Company.create(ticker: "ALK", name: "Alaska Air Group Inc", logo: "https://logo.clearbit.com/Alaska.com", sector: "Industrials")
alb = Company.create(ticker: "ALB", name: "Albemarle Corp", logo: "https://logo.clearbit.com/Albemarle.com", sector: "Materials")
are = Company.create(ticker: "ARE", name: "Alexandria Real Estate Equities", logo: "https://logo.clearbit.com/Alexandria.com", sector: "Real Estate")
alxn = Company.create(ticker: "ALXN", name: "Alexion Pharmaceuticals", logo: "https://logo.clearbit.com/Alexion.com", sector: "Health Care")
algn = Company.create(ticker: "ALGN", name: "Align Technology", logo: "https://logo.clearbit.com/Align.com", sector: "Health Care")
alle = Company.create(ticker: "ALLE", name: "Allegion", logo: "https://logo.clearbit.com/Allegion.com", sector: "Industrials")
lnt = Company.create(ticker: "LNT", name: "Alliant Energy Corp", logo: "https://logo.clearbit.com/Alliant.com", sector: "Utilities")
all = Company.create(ticker: "ALL", name: "Allstate Corp", logo: "https://logo.clearbit.com/Allstate.com", sector: "Financials")
googl = Company.create(ticker: "GOOGL", name: "Alphabet Inc. (Class A)", logo: "https://logo.clearbit.com/Alphabet.com", sector: "Communication Services")
goog = Company.create(ticker: "GOOG", name: "Alphabet Inc. (Class C)", logo: "https://logo.clearbit.com/Alphabet.com", sector: "Communication Services")
mo = Company.create(ticker: "MO", name: "Altria Group Inc", logo: "https://logo.clearbit.com/Altria.com", sector: "Consumer Staples")
amzn = Company.create(ticker: "AMZN", name: "Amazon.com Inc.", logo: "https://logo.clearbit.com/Amazon.com.com", sector: "Consumer Discretionary")
amcr = Company.create(ticker: "AMCR", name: "Amcor plc", logo: "https://logo.clearbit.com/Amcor.com", sector: "Materials")
aee = Company.create(ticker: "AEE", name: "Ameren Corp", logo: "https://logo.clearbit.com/Ameren.com", sector: "Utilities")
aal = Company.create(ticker: "AAL", name: "American Airlines Group", logo: "https://logo.clearbit.com/American.com", sector: "Industrials")
aep = Company.create(ticker: "AEP", name: "American Electric Power", logo: "https://logo.clearbit.com/American.com", sector: "Utilities")
axp = Company.create(ticker: "AXP", name: "American Express Co", logo: "https://logo.clearbit.com/American.com", sector: "Financials")
aig = Company.create(ticker: "AIG", name: "American International Group", logo: "https://logo.clearbit.com/American.com", sector: "Financials")
amt = Company.create(ticker: "AMT", name: "American Tower Corp.", logo: "https://logo.clearbit.com/American.com", sector: "Real Estate")
awk = Company.create(ticker: "AWK", name: "American Water Works Company Inc", logo: "https://logo.clearbit.com/American.com", sector: "Utilities")
amp = Company.create(ticker: "AMP", name: "Ameriprise Financial", logo: "https://logo.clearbit.com/Ameriprise.com", sector: "Financials")
abc = Company.create(ticker: "ABC", name: "AmerisourceBergen Corp", logo: "https://logo.clearbit.com/AmerisourceBergen.com", sector: "Health Care")
ame = Company.create(ticker: "AME", name: "AMETEK Inc.", logo: "https://logo.clearbit.com/AMETEK.com", sector: "Industrials")
amgn = Company.create(ticker: "AMGN", name: "Amgen Inc.", logo: "https://logo.clearbit.com/Amgen.com", sector: "Health Care")
aph = Company.create(ticker: "APH", name: "Amphenol Corp", logo: "https://logo.clearbit.com/Amphenol.com", sector: "Information Technology")
adi = Company.create(ticker: "ADI", name: "Analog Devices, Inc.", logo: "https://logo.clearbit.com/Analog.com", sector: "Information Technology")
anss = Company.create(ticker: "ANSS", name: "ANSYS", logo: "https://logo.clearbit.com/ANSYS.com", sector: "Information Technology")
antm = Company.create(ticker: "ANTM", name: "Anthem", logo: "https://logo.clearbit.com/Anthem.com", sector: "Health Care")
aon = Company.create(ticker: "AON", name: "Aon plc", logo: "https://logo.clearbit.com/Aon.com", sector: "Financials")
aos = Company.create(ticker: "AOS", name: "A.O. Smith Corp", logo: "https://logo.clearbit.com/A.O..com", sector: "Industrials")
apa = Company.create(ticker: "APA", name: "Apache Corporation", logo: "https://logo.clearbit.com/Apache.com", sector: "Energy")
aiv = Company.create(ticker: "AIV", name: "Apartment Investment & Management", logo: "https://logo.clearbit.com/Apartment.com", sector: "Real Estate")
aapl = Company.create(ticker: "AAPL", name: "Apple Inc.", logo: "https://logo.clearbit.com/Apple.com", sector: "Information Technology")
amat = Company.create(ticker: "AMAT", name: "Applied Materials Inc.", logo: "https://logo.clearbit.com/Applied.com", sector: "Information Technology")
aptv = Company.create(ticker: "APTV", name: "Aptiv PLC", logo: "https://logo.clearbit.com/Aptiv.com", sector: "Consumer Discretionary")
adm = Company.create(ticker: "ADM", name: "Archer-Daniels-Midland Co", logo: "https://logo.clearbit.com/Archer-Daniels-Midland.com", sector: "Consumer Staples")
anet = Company.create(ticker: "ANET", name: "Arista Networks", logo: "https://logo.clearbit.com/Arista.com", sector: "Information Technology")
ajg = Company.create(ticker: "AJG", name: "Arthur J. Gallagher & Co.", logo: "https://logo.clearbit.com/Arthur.com", sector: "Financials")
aiz = Company.create(ticker: "AIZ", name: "Assurant", logo: "https://logo.clearbit.com/Assurant.com", sector: "Financials")
t = Company.create(ticker: "T", name: "AT&T Inc.", logo: "https://logo.clearbit.com/AT&T.com", sector: "Communication Services")
ato = Company.create(ticker: "ATO", name: "Atmos Energy", logo: "https://logo.clearbit.com/Atmos.com", sector: "Utilities")
adsk = Company.create(ticker: "ADSK", name: "Autodesk Inc.", logo: "https://logo.clearbit.com/Autodesk.com", sector: "Information Technology")
adp = Company.create(ticker: "ADP", name: "Automatic Data Processing", logo: "https://logo.clearbit.com/Automatic.com", sector: "Information Technology")
azo = Company.create(ticker: "AZO", name: "AutoZone Inc", logo: "https://logo.clearbit.com/AutoZone.com", sector: "Consumer Discretionary")
avb = Company.create(ticker: "AVB", name: "AvalonBay Communities", logo: "https://logo.clearbit.com/AvalonBay.com", sector: "Real Estate")
avy = Company.create(ticker: "AVY", name: "Avery Dennison Corp", logo: "https://logo.clearbit.com/Avery.com", sector: "Materials")
bkr = Company.create(ticker: "BKR", name: "Baker Hughes Co", logo: "https://logo.clearbit.com/Baker.com", sector: "Energy")
bll = Company.create(ticker: "BLL", name: "Ball Corp", logo: "https://logo.clearbit.com/Ball.com", sector: "Materials")
bac = Company.create(ticker: "BAC", name: "Bank of America Corp", logo: "https://logo.clearbit.com/Bank.com", sector: "Financials")
bk = Company.create(ticker: "BK", name: "The Bank of New York Mellon", logo: "https://logo.clearbit.com/The.com", sector: "Financials")
bax = Company.create(ticker: "BAX", name: "Baxter International Inc.", logo: "https://logo.clearbit.com/Baxter.com", sector: "Health Care")
bdx = Company.create(ticker: "BDX", name: "Becton Dickinson", logo: "https://logo.clearbit.com/Becton.com", sector: "Health Care")
brkb = Company.create(ticker: "BRK-B", name: "Berkshire Hathaway", logo: "https://logo.clearbit.com/Berkshire.com", sector: "Financials")
bby = Company.create(ticker: "BBY", name: "Best Buy Co. Inc.", logo: "https://logo.clearbit.com/Best.com", sector: "Consumer Discretionary")
biib = Company.create(ticker: "BIIB", name: "Biogen Inc.", logo: "https://logo.clearbit.com/Biogen.com", sector: "Health Care")
bio = Company.create(ticker: "BIO", name: "Bio-Rad Laboratories", logo: "https://logo.clearbit.com/Bio-Rad.com", sector: "Health Care")
blk = Company.create(ticker: "BLK", name: "BlackRock", logo: "https://logo.clearbit.com/BlackRock.com", sector: "Financials")
ba = Company.create(ticker: "BA", name: "Boeing Company", logo: "https://logo.clearbit.com/Boeing.com", sector: "Industrials")
bkng = Company.create(ticker: "BKNG", name: "Booking Holdings Inc", logo: "https://logo.clearbit.com/Booking.com", sector: "Consumer Discretionary")
bwa = Company.create(ticker: "BWA", name: "BorgWarner", logo: "https://logo.clearbit.com/BorgWarner.com", sector: "Consumer Discretionary")
bxp = Company.create(ticker: "BXP", name: "Boston Properties", logo: "https://logo.clearbit.com/Boston.com", sector: "Real Estate")
bsx = Company.create(ticker: "BSX", name: "Boston Scientific", logo: "https://logo.clearbit.com/Boston.com", sector: "Health Care")
bmy = Company.create(ticker: "BMY", name: "Bristol-Myers Squibb", logo: "https://logo.clearbit.com/Bristol-Myers.com", sector: "Health Care")
avgo = Company.create(ticker: "AVGO", name: "Broadcom Inc.", logo: "https://logo.clearbit.com/Broadcom.com", sector: "Information Technology")
br = Company.create(ticker: "BR", name: "Broadridge Financial Solutions", logo: "https://logo.clearbit.com/Broadridge.com", sector: "Information Technology")
bfb = Company.create(ticker: "BF-B", name: "Brown-Forman Corp.", logo: "https://logo.clearbit.com/Brown-Forman.com", sector: "Consumer Staples")
chrw = Company.create(ticker: "CHRW", name: "C. H. Robinson Worldwide", logo: "https://logo.clearbit.com/C..com", sector: "Industrials")
cog = Company.create(ticker: "COG", name: "Cabot Oil & Gas", logo: "https://logo.clearbit.com/Cabot.com", sector: "Energy")
cdns = Company.create(ticker: "CDNS", name: "Cadence Design Systems", logo: "https://logo.clearbit.com/Cadence.com", sector: "Information Technology")
cpb = Company.create(ticker: "CPB", name: "Campbell Soup", logo: "https://logo.clearbit.com/Campbell.com", sector: "Consumer Staples")
cof = Company.create(ticker: "COF", name: "Capital One Financial", logo: "https://logo.clearbit.com/Capital.com", sector: "Financials")
cah = Company.create(ticker: "CAH", name: "Cardinal Health Inc.", logo: "https://logo.clearbit.com/Cardinal.com", sector: "Health Care")
kmx = Company.create(ticker: "KMX", name: "Carmax Inc", logo: "https://logo.clearbit.com/Carmax.com", sector: "Consumer Discretionary")
ccl = Company.create(ticker: "CCL", name: "Carnival Corp.", logo: "https://logo.clearbit.com/Carnival.com", sector: "Consumer Discretionary")
carr = Company.create(ticker: "CARR", name: "Carrier Global", logo: "https://logo.clearbit.com/Carrier.com", sector: "Industrials")
cat = Company.create(ticker: "CAT", name: "Caterpillar Inc.", logo: "https://logo.clearbit.com/Caterpillar.com", sector: "Industrials")
cboe = Company.create(ticker: "CBOE", name: "Cboe Global Markets", logo: "https://logo.clearbit.com/Cboe.com", sector: "Financials")
cbre = Company.create(ticker: "CBRE", name: "CBRE Group", logo: "https://logo.clearbit.com/CBRE.com", sector: "Real Estate")
cdw = Company.create(ticker: "CDW", name: "CDW", logo: "https://logo.clearbit.com/CDW.com", sector: "Information Technology")
ce = Company.create(ticker: "CE", name: "Celanese", logo: "https://logo.clearbit.com/Celanese.com", sector: "Materials")
cnc = Company.create(ticker: "CNC", name: "Centene Corporation", logo: "https://logo.clearbit.com/Centene.com", sector: "Health Care")
cnp = Company.create(ticker: "CNP", name: "CenterPoint Energy", logo: "https://logo.clearbit.com/CenterPoint.com", sector: "Utilities")
ctl = Company.create(ticker: "CTL", name: "CenturyLink Inc", logo: "https://logo.clearbit.com/CenturyLink.com", sector: "Communication Services")
cern = Company.create(ticker: "CERN", name: "Cerner", logo: "https://logo.clearbit.com/Cerner.com", sector: "Health Care")
cf = Company.create(ticker: "CF", name: "CF Industries Holdings Inc", logo: "https://logo.clearbit.com/CF.com", sector: "Materials")
schw = Company.create(ticker: "SCHW", name: "Charles Schwab Corporation", logo: "https://logo.clearbit.com/Charles.com", sector: "Financials")
chtr = Company.create(ticker: "CHTR", name: "Charter Communications", logo: "https://logo.clearbit.com/Charter.com", sector: "Communication Services")
cvx = Company.create(ticker: "CVX", name: "Chevron Corp.", logo: "https://logo.clearbit.com/Chevron.com", sector: "Energy")
cmg = Company.create(ticker: "CMG", name: "Chipotle Mexican Grill", logo: "https://logo.clearbit.com/Chipotle.com", sector: "Consumer Discretionary")
cb = Company.create(ticker: "CB", name: "Chubb Limited", logo: "https://logo.clearbit.com/Chubb.com", sector: "Financials")
chd = Company.create(ticker: "CHD", name: "Church & Dwight", logo: "https://logo.clearbit.com/Church.com", sector: "Consumer Staples")
ci = Company.create(ticker: "CI", name: "CIGNA Corp.", logo: "https://logo.clearbit.com/CIGNA.com", sector: "Health Care")
cinf = Company.create(ticker: "CINF", name: "Cincinnati Financial", logo: "https://logo.clearbit.com/Cincinnati.com", sector: "Financials")
ctas = Company.create(ticker: "CTAS", name: "Cintas Corporation", logo: "https://logo.clearbit.com/Cintas.com", sector: "Industrials")
csco = Company.create(ticker: "CSCO", name: "Cisco Systems", logo: "https://logo.clearbit.com/Cisco.com", sector: "Information Technology")
c = Company.create(ticker: "C", name: "Citigroup Inc.", logo: "https://logo.clearbit.com/Citigroup.com", sector: "Financials")
cfg = Company.create(ticker: "CFG", name: "Citizens Financial Group", logo: "https://logo.clearbit.com/Citizens.com", sector: "Financials")
ctxs = Company.create(ticker: "CTXS", name: "Citrix Systems", logo: "https://logo.clearbit.com/Citrix.com", sector: "Information Technology")
clx = Company.create(ticker: "CLX", name: "The Clorox Company", logo: "https://logo.clearbit.com/The.com", sector: "Consumer Staples")
cme = Company.create(ticker: "CME", name: "CME Group Inc.", logo: "https://logo.clearbit.com/CME.com", sector: "Financials")
cms = Company.create(ticker: "CMS", name: "CMS Energy", logo: "https://logo.clearbit.com/CMS.com", sector: "Utilities")
ko = Company.create(ticker: "KO", name: "Coca-Cola Company", logo: "https://logo.clearbit.com/Coca-Cola.com", sector: "Consumer Staples")
ctsh = Company.create(ticker: "CTSH", name: "Cognizant Technology Solutions", logo: "https://logo.clearbit.com/Cognizant.com", sector: "Information Technology")
cl = Company.create(ticker: "CL", name: "Colgate-Palmolive", logo: "https://logo.clearbit.com/Colgate-Palmolive.com", sector: "Consumer Staples")
cmcsa = Company.create(ticker: "CMCSA", name: "Comcast Corp.", logo: "https://logo.clearbit.com/Comcast.com", sector: "Communication Services")
cma = Company.create(ticker: "CMA", name: "Comerica Inc.", logo: "https://logo.clearbit.com/Comerica.com", sector: "Financials")
cag = Company.create(ticker: "CAG", name: "Conagra Brands", logo: "https://logo.clearbit.com/Conagra.com", sector: "Consumer Staples")
cxo = Company.create(ticker: "CXO", name: "Concho Resources", logo: "https://logo.clearbit.com/Concho.com", sector: "Energy")
cop = Company.create(ticker: "COP", name: "ConocoPhillips", logo: "https://logo.clearbit.com/ConocoPhillips.com", sector: "Energy")
ed = Company.create(ticker: "ED", name: "Consolidated Edison", logo: "https://logo.clearbit.com/Consolidated.com", sector: "Utilities")
stz = Company.create(ticker: "STZ", name: "Constellation Brands", logo: "https://logo.clearbit.com/Constellation.com", sector: "Consumer Staples")
coo = Company.create(ticker: "COO", name: "The Cooper Companies", logo: "https://logo.clearbit.com/The.com", sector: "Health Care")
cprt = Company.create(ticker: "CPRT", name: "Copart Inc", logo: "https://logo.clearbit.com/Copart.com", sector: "Industrials")
glw = Company.create(ticker: "GLW", name: "Corning Inc.", logo: "https://logo.clearbit.com/Corning.com", sector: "Information Technology")
ctva = Company.create(ticker: "CTVA", name: "Corteva", logo: "https://logo.clearbit.com/Corteva.com", sector: "Materials")
cost = Company.create(ticker: "COST", name: "Costco Wholesale Corp.", logo: "https://logo.clearbit.com/Costco.com", sector: "Consumer Staples")
coty = Company.create(ticker: "COTY", name: "Coty, Inc", logo: "https://logo.clearbit.com/Coty,.com", sector: "Consumer Staples")
cci = Company.create(ticker: "CCI", name: "Crown Castle International Corp.", logo: "https://logo.clearbit.com/Crown.com", sector: "Real Estate")
csx = Company.create(ticker: "CSX", name: "CSX Corp.", logo: "https://logo.clearbit.com/CSX.com", sector: "Industrials")
cmi = Company.create(ticker: "CMI", name: "Cummins Inc.", logo: "https://logo.clearbit.com/Cummins.com", sector: "Industrials")
cvs = Company.create(ticker: "CVS", name: "CVS Health", logo: "https://logo.clearbit.com/CVS.com", sector: "Health Care")
dhi = Company.create(ticker: "DHI", name: "D. R. Horton", logo: "https://logo.clearbit.com/D..com", sector: "Consumer Discretionary")
dhr = Company.create(ticker: "DHR", name: "Danaher Corp.", logo: "https://logo.clearbit.com/Danaher.com", sector: "Health Care")
dri = Company.create(ticker: "DRI", name: "Darden Restaurants", logo: "https://logo.clearbit.com/Darden.com", sector: "Consumer Discretionary")
dva = Company.create(ticker: "DVA", name: "DaVita Inc.", logo: "https://logo.clearbit.com/DaVita.com", sector: "Health Care")
de = Company.create(ticker: "DE", name: "Deere & Co.", logo: "https://logo.clearbit.com/Deere.com", sector: "Industrials")
dal = Company.create(ticker: "DAL", name: "Delta Air Lines Inc.", logo: "https://logo.clearbit.com/Delta.com", sector: "Industrials")
xray = Company.create(ticker: "XRAY", name: "Dentsply Sirona", logo: "https://logo.clearbit.com/Dentsply.com", sector: "Health Care")
dvn = Company.create(ticker: "DVN", name: "Devon Energy", logo: "https://logo.clearbit.com/Devon.com", sector: "Energy")
dxcm = Company.create(ticker: "DXCM", name: "DexCom", logo: "https://logo.clearbit.com/DexCom.com", sector: "Health Care")
fang = Company.create(ticker: "FANG", name: "Diamondback Energy", logo: "https://logo.clearbit.com/Diamondback.com", sector: "Energy")
dlr = Company.create(ticker: "DLR", name: "Digital Realty Trust Inc", logo: "https://logo.clearbit.com/Digital.com", sector: "Real Estate")
dfs = Company.create(ticker: "DFS", name: "Discover Financial Services", logo: "https://logo.clearbit.com/Discover.com", sector: "Financials")
disca = Company.create(ticker: "DISCA", name: "Discovery, Inc. (Class A)", logo: "https://logo.clearbit.com/Discovery,.com", sector: "Communication Services")
disck = Company.create(ticker: "DISCK", name: "Discovery, Inc. (Class C)", logo: "https://logo.clearbit.com/Discovery,.com", sector: "Communication Services")
dish = Company.create(ticker: "DISH", name: "Dish Network", logo: "https://logo.clearbit.com/Dish.com", sector: "Communication Services")
dg = Company.create(ticker: "DG", name: "Dollar General", logo: "https://logo.clearbit.com/Dollar.com", sector: "Consumer Discretionary")
dltr = Company.create(ticker: "DLTR", name: "Dollar Tree", logo: "https://logo.clearbit.com/Dollar.com", sector: "Consumer Discretionary")
d = Company.create(ticker: "D", name: "Dominion Energy", logo: "https://logo.clearbit.com/Dominion.com", sector: "Utilities")
dpz = Company.create(ticker: "DPZ", name: "Domino's Pizza", logo: 'https://logo.clearbit.com/Dominos.com', sector: "Consumer Discretionary")
dov = Company.create(ticker: "DOV", name: "Dover Corporation", logo: "https://logo.clearbit.com/Dover.com", sector: "Industrials")
dow = Company.create(ticker: "DOW", name: "Dow Inc.", logo: "https://logo.clearbit.com/Dow.com", sector: "Materials")
dte = Company.create(ticker: "DTE", name: "DTE Energy Co.", logo: "https://logo.clearbit.com/DTE.com", sector: "Utilities")
duk = Company.create(ticker: "DUK", name: "Duke Energy", logo: "https://logo.clearbit.com/Duke.com", sector: "Utilities")
dre = Company.create(ticker: "DRE", name: "Duke Realty Corp", logo: "https://logo.clearbit.com/Duke.com", sector: "Real Estate")
dd = Company.create(ticker: "DD", name: "DuPont de Nemours Inc", logo: "https://logo.clearbit.com/DuPont.com", sector: "Materials")
dxc = Company.create(ticker: "DXC", name: "DXC Technology", logo: "https://logo.clearbit.com/DXC.com", sector: "Information Technology")
etfc = Company.create(ticker: "ETFC", name: "E*Trade", logo: "https://logo.clearbit.com/E*Trade.com", sector: "Financials")
emn = Company.create(ticker: "EMN", name: "Eastman Chemical", logo: "https://logo.clearbit.com/Eastman.com", sector: "Materials")
etn = Company.create(ticker: "ETN", name: "Eaton Corporation", logo: "https://logo.clearbit.com/Eaton.com", sector: "Industrials")
ebay = Company.create(ticker: "EBAY", name: "eBay Inc.", logo: "https://logo.clearbit.com/eBay.com", sector: "Consumer Discretionary")
ecl = Company.create(ticker: "ECL", name: "Ecolab Inc.", logo: "https://logo.clearbit.com/Ecolab.com", sector: "Materials")
eix = Company.create(ticker: "EIX", name: "Edison Int'l", logo: "https://logo.clearbit.com/Edison.com", sector: "Utilities")
ew = Company.create(ticker: "EW", name: "Edwards Lifesciences", logo: "https://logo.clearbit.com/Edwards.com", sector: "Health Care")
ea = Company.create(ticker: "EA", name: "Electronic Arts", logo: "https://logo.clearbit.com/Electronic.com", sector: "Communication Services")
emr = Company.create(ticker: "EMR", name: "Emerson Electric Company", logo: "https://logo.clearbit.com/Emerson.com", sector: "Industrials")
etr = Company.create(ticker: "ETR", name: "Entergy Corp.", logo: "https://logo.clearbit.com/Entergy.com", sector: "Utilities")
eog = Company.create(ticker: "EOG", name: "EOG Resources", logo: "https://logo.clearbit.com/EOG.com", sector: "Energy")
efx = Company.create(ticker: "EFX", name: "Equifax Inc.", logo: "https://logo.clearbit.com/Equifax.com", sector: "Industrials")
eqix = Company.create(ticker: "EQIX", name: "Equinix", logo: "https://logo.clearbit.com/Equinix.com", sector: "Real Estate")
eqr = Company.create(ticker: "EQR", name: "Equity Residential", logo: "https://logo.clearbit.com/Equity.com", sector: "Real Estate")
ess = Company.create(ticker: "ESS", name: "Essex Property Trust, Inc.", logo: "https://logo.clearbit.com/Essex.com", sector: "Real Estate")
el = Company.create(ticker: "EL", name: "Estée Lauder Companies", logo: "https://logo.clearbit.com/Estée.com", sector: "Consumer Staples")
evrg = Company.create(ticker: "EVRG", name: "Evergy", logo: "https://logo.clearbit.com/Evergy.com", sector: "Utilities")
es = Company.create(ticker: "ES", name: "Eversource Energy", logo: "https://logo.clearbit.com/Eversource.com", sector: "Utilities")
re = Company.create(ticker: "RE", name: "Everest Re Group Ltd.", logo: "https://logo.clearbit.com/Everest.com", sector: "Financials")
exc = Company.create(ticker: "EXC", name: "Exelon Corp.", logo: "https://logo.clearbit.com/Exelon.com", sector: "Utilities")
expe = Company.create(ticker: "EXPE", name: "Expedia Group", logo: "https://logo.clearbit.com/Expedia.com", sector: "Consumer Discretionary")
expd = Company.create(ticker: "EXPD", name: "Expeditors", logo: "https://logo.clearbit.com/Expeditors.com", sector: "Industrials")
exr = Company.create(ticker: "EXR", name: "Extra Space Storage", logo: "https://logo.clearbit.com/Extra.com", sector: "Real Estate")
xom = Company.create(ticker: "XOM", name: "Exxon Mobil Corp.", logo: "https://logo.clearbit.com/Exxon.com", sector: "Energy")
ffiv = Company.create(ticker: "FFIV", name: "F5 Networks", logo: "https://logo.clearbit.com/F5.com", sector: "Information Technology")
fb = Company.create(ticker: "FB", name: "Facebook, Inc.", logo: "https://logo.clearbit.com/Facebook,.com", sector: "Communication Services")
fast = Company.create(ticker: "FAST", name: "Fastenal Co", logo: "https://logo.clearbit.com/Fastenal.com", sector: "Industrials")
frt = Company.create(ticker: "FRT", name: "Federal Realty Investment Trust", logo: "https://logo.clearbit.com/Federal.com", sector: "Real Estate")
fdx = Company.create(ticker: "FDX", name: "FedEx Corporation", logo: "https://logo.clearbit.com/FedEx.com", sector: "Industrials")
fis = Company.create(ticker: "FIS", name: "Fidelity National Information Services", logo: "https://logo.clearbit.com/Fidelity.com", sector: "Information Technology")
fitb = Company.create(ticker: "FITB", name: "Fifth Third Bancorp", logo: "https://logo.clearbit.com/Fifth.com", sector: "Financials")
fe = Company.create(ticker: "FE", name: "FirstEnergy Corp", logo: "https://logo.clearbit.com/FirstEnergy.com", sector: "Utilities")
frc = Company.create(ticker: "FRC", name: "First Republic Bank", logo: "https://logo.clearbit.com/First.com", sector: "Financials")
fisv = Company.create(ticker: "FISV", name: "Fiserv Inc", logo: "https://logo.clearbit.com/Fiserv.com", sector: "Information Technology")
flt = Company.create(ticker: "FLT", name: "FleetCor Technologies Inc", logo: "https://logo.clearbit.com/FleetCor.com", sector: "Information Technology")
flir = Company.create(ticker: "FLIR", name: "FLIR Systems", logo: "https://logo.clearbit.com/FLIR.com", sector: "Information Technology")
fls = Company.create(ticker: "FLS", name: "Flowserve Corporation", logo: "https://logo.clearbit.com/Flowserve.com", sector: "Industrials")
fmc = Company.create(ticker: "FMC", name: "FMC Corporation", logo: "https://logo.clearbit.com/FMC.com", sector: "Materials")
f = Company.create(ticker: "F", name: "Ford Motor Company", logo: "https://logo.clearbit.com/Ford.com", sector: "Consumer Discretionary")
ftnt = Company.create(ticker: "FTNT", name: "Fortinet", logo: "https://logo.clearbit.com/Fortinet.com", sector: "Information Technology")
ftv = Company.create(ticker: "FTV", name: "Fortive Corp", logo: "https://logo.clearbit.com/Fortive.com", sector: "Industrials")
fbhs = Company.create(ticker: "FBHS", name: "Fortune Brands Home & Security", logo: "https://logo.clearbit.com/Fortune.com", sector: "Industrials")
foxa = Company.create(ticker: "FOXA", name: "Fox Corporation (Class A)", logo: "https://logo.clearbit.com/Fox.com", sector: "Communication Services")
fox = Company.create(ticker: "FOX", name: "Fox Corporation (Class B)", logo: "https://logo.clearbit.com/Fox.com", sector: "Communication Services")
ben = Company.create(ticker: "BEN", name: "Franklin Resources", logo: "https://logo.clearbit.com/Franklin.com", sector: "Financials")
fcx = Company.create(ticker: "FCX", name: "Freeport-McMoRan Inc.", logo: "https://logo.clearbit.com/Freeport-McMoRan.com", sector: "Materials")
gps = Company.create(ticker: "GPS", name: "Gap Inc.", logo: "https://logo.clearbit.com/Gap.com", sector: "Consumer Discretionary")
grmn = Company.create(ticker: "GRMN", name: "Garmin Ltd.", logo: "https://logo.clearbit.com/Garmin.com", sector: "Consumer Discretionary")
it = Company.create(ticker: "IT", name: "Gartner Inc", logo: "https://logo.clearbit.com/Gartner.com", sector: "Information Technology")
gd = Company.create(ticker: "GD", name: "General Dynamics", logo: "https://logo.clearbit.com/General.com", sector: "Industrials")
ge = Company.create(ticker: "GE", name: "General Electric", logo: "https://logo.clearbit.com/General.com", sector: "Industrials")
gis = Company.create(ticker: "GIS", name: "General Mills", logo: "https://logo.clearbit.com/General.com", sector: "Consumer Staples")
gm = Company.create(ticker: "GM", name: "General Motors", logo: "https://logo.clearbit.com/General.com", sector: "Consumer Discretionary")
gpc = Company.create(ticker: "GPC", name: "Genuine Parts", logo: "https://logo.clearbit.com/Genuine.com", sector: "Consumer Discretionary")
gild = Company.create(ticker: "GILD", name: "Gilead Sciences", logo: "https://logo.clearbit.com/Gilead.com", sector: "Health Care")
gl = Company.create(ticker: "GL", name: "Globe Life Inc.", logo: "https://logo.clearbit.com/Globe.com", sector: "Financials")
gpn = Company.create(ticker: "GPN", name: "Global Payments Inc.", logo: "https://logo.clearbit.com/Global.com", sector: "Information Technology")
gs = Company.create(ticker: "GS", name: "Goldman Sachs Group", logo: "https://logo.clearbit.com/Goldman.com", sector: "Financials")
gww = Company.create(ticker: "GWW", name: "Grainger (W.W.) Inc.", logo: "https://logo.clearbit.com/Grainger.com", sector: "Industrials")
hrb = Company.create(ticker: "HRB", name: "H&R Block", logo: "https://logo.clearbit.com/H&R.com", sector: "Consumer Discretionary")
hal = Company.create(ticker: "HAL", name: "Halliburton Co.", logo: "https://logo.clearbit.com/Halliburton.com", sector: "Energy")
hbi = Company.create(ticker: "HBI", name: "Hanesbrands Inc", logo: "https://logo.clearbit.com/Hanesbrands.com", sector: "Consumer Discretionary")
hig = Company.create(ticker: "HIG", name: "Hartford Financial Svc.Gp.", logo: "https://logo.clearbit.com/Hartford.com", sector: "Financials")
has = Company.create(ticker: "HAS", name: "Hasbro Inc.", logo: "https://logo.clearbit.com/Hasbro.com", sector: "Consumer Discretionary")
hca = Company.create(ticker: "HCA", name: "HCA Healthcare", logo: "https://logo.clearbit.com/HCA.com", sector: "Health Care")
peak = Company.create(ticker: "PEAK", name: "Healthpeak Properties", logo: "https://logo.clearbit.com/Healthpeak.com", sector: "Real Estate")
hsic = Company.create(ticker: "HSIC", name: "Henry Schein", logo: "https://logo.clearbit.com/Henry.com", sector: "Health Care")
hsy = Company.create(ticker: "HSY", name: "The Hershey Company", logo: "https://logo.clearbit.com/The.com", sector: "Consumer Staples")
hes = Company.create(ticker: "HES", name: "Hess Corporation", logo: "https://logo.clearbit.com/Hess.com", sector: "Energy")
hpe = Company.create(ticker: "HPE", name: "Hewlett Packard Enterprise", logo: "https://logo.clearbit.com/Hewlett.com", sector: "Information Technology")
hlt = Company.create(ticker: "HLT", name: "Hilton Worldwide Holdings Inc", logo: "https://logo.clearbit.com/Hilton.com", sector: "Consumer Discretionary")
hfc = Company.create(ticker: "HFC", name: "HollyFrontier Corp", logo: "https://logo.clearbit.com/HollyFrontier.com", sector: "Energy")
holx = Company.create(ticker: "HOLX", name: "Hologic", logo: "https://logo.clearbit.com/Hologic.com", sector: "Health Care")
hd = Company.create(ticker: "HD", name: "Home Depot", logo: "https://logo.clearbit.com/Home.com", sector: "Consumer Discretionary")
hon = Company.create(ticker: "HON", name: "Honeywell Int'l Inc.", logo: "https://logo.clearbit.com/Honeywell.com", sector: "Industrials")
hrl = Company.create(ticker: "HRL", name: "Hormel Foods Corp.", logo: "https://logo.clearbit.com/Hormel.com", sector: "Consumer Staples")
hst = Company.create(ticker: "HST", name: "Host Hotels & Resorts", logo: "https://logo.clearbit.com/Host.com", sector: "Real Estate")
hwm = Company.create(ticker: "HWM", name: "Howmet Aerospace", logo: "https://logo.clearbit.com/Howmet.com", sector: "Industrials")
hpq = Company.create(ticker: "HPQ", name: "HP Inc.", logo: "https://logo.clearbit.com/HP.com", sector: "Information Technology")
hum = Company.create(ticker: "HUM", name: "Humana Inc.", logo: "https://logo.clearbit.com/Humana.com", sector: "Health Care")
hban = Company.create(ticker: "HBAN", name: "Huntington Bancshares", logo: "https://logo.clearbit.com/Huntington.com", sector: "Financials")
hii = Company.create(ticker: "HII", name: "Huntington Ingalls Industries", logo: "https://logo.clearbit.com/Huntington.com", sector: "Industrials")
iex = Company.create(ticker: "IEX", name: "IDEX Corporation", logo: "https://logo.clearbit.com/IDEX.com", sector: "Industrials")
idxx = Company.create(ticker: "IDXX", name: "IDEXX Laboratories", logo: "https://logo.clearbit.com/IDEXX.com", sector: "Health Care")
info = Company.create(ticker: "INFO", name: "IHS Markit Ltd.", logo: "https://logo.clearbit.com/IHS.com", sector: "Industrials")
itw = Company.create(ticker: "ITW", name: "Illinois Tool Works", logo: "https://logo.clearbit.com/Illinois.com", sector: "Industrials")
ilmn = Company.create(ticker: "ILMN", name: "Illumina Inc", logo: "https://logo.clearbit.com/Illumina.com", sector: "Health Care")
incy = Company.create(ticker: "INCY", name: "Incyte", logo: "https://logo.clearbit.com/Incyte.com", sector: "Health Care")
ir = Company.create(ticker: "IR", name: "Ingersoll Rand", logo: "https://logo.clearbit.com/Ingersoll.com", sector: "Industrials")
intc = Company.create(ticker: "INTC", name: "Intel Corp.", logo: "https://logo.clearbit.com/Intel.com", sector: "Information Technology")
ice = Company.create(ticker: "ICE", name: "Intercontinental Exchange", logo: "https://logo.clearbit.com/Intercontinental.com", sector: "Financials")
ibm = Company.create(ticker: "IBM", name: "International Business Machines", logo: "https://logo.clearbit.com/International.com", sector: "Information Technology")
ip = Company.create(ticker: "IP", name: "International Paper", logo: "https://logo.clearbit.com/International.com", sector: "Materials")
ipg = Company.create(ticker: "IPG", name: "Interpublic Group", logo: "https://logo.clearbit.com/Interpublic.com", sector: "Communication Services")
iff = Company.create(ticker: "IFF", name: "Intl Flavors & Fragrances", logo: "https://logo.clearbit.com/Intl.com", sector: "Materials")
intu = Company.create(ticker: "INTU", name: "Intuit Inc.", logo: "https://logo.clearbit.com/Intuit.com", sector: "Information Technology")
isrg = Company.create(ticker: "ISRG", name: "Intuitive Surgical Inc.", logo: "https://logo.clearbit.com/Intuitive.com", sector: "Health Care")
ivz = Company.create(ticker: "IVZ", name: "Invesco Ltd.", logo: "https://logo.clearbit.com/Invesco.com", sector: "Financials")
ipgp = Company.create(ticker: "IPGP", name: "IPG Photonics Corp.", logo: "https://logo.clearbit.com/IPG.com", sector: "Information Technology")
iqv = Company.create(ticker: "IQV", name: "IQVIA Holdings Inc.", logo: "https://logo.clearbit.com/IQVIA.com", sector: "Health Care")
irm = Company.create(ticker: "IRM", name: "Iron Mountain Incorporated", logo: "https://logo.clearbit.com/Iron.com", sector: "Real Estate")
jkhy = Company.create(ticker: "JKHY", name: "Jack Henry & Associates", logo: "https://logo.clearbit.com/Jack.com", sector: "Information Technology")
j = Company.create(ticker: "J", name: "Jacobs Engineering Group", logo: "https://logo.clearbit.com/Jacobs.com", sector: "Industrials")
jbht = Company.create(ticker: "JBHT", name: "J. B. Hunt Transport Services", logo: "https://logo.clearbit.com/J..com", sector: "Industrials")
sjm = Company.create(ticker: "SJM", name: "JM Smucker", logo: "https://logo.clearbit.com/JM.com", sector: "Consumer Staples")
jnj = Company.create(ticker: "JNJ", name: "Johnson & Johnson", logo: "https://logo.clearbit.com/Johnson.com", sector: "Health Care")
jci = Company.create(ticker: "JCI", name: "Johnson Controls International", logo: "https://logo.clearbit.com/Johnson.com", sector: "Industrials")
jpm = Company.create(ticker: "JPM", name: "JPMorgan Chase & Co.", logo: "https://logo.clearbit.com/JPMorgan.com", sector: "Financials")
jnpr = Company.create(ticker: "JNPR", name: "Juniper Networks", logo: "https://logo.clearbit.com/Juniper.com", sector: "Information Technology")
ksu = Company.create(ticker: "KSU", name: "Kansas City Southern", logo: "https://logo.clearbit.com/Kansas.com", sector: "Industrials")
k = Company.create(ticker: "K", name: "Kellogg Co.", logo: "https://logo.clearbit.com/Kellogg.com", sector: "Consumer Staples")
key = Company.create(ticker: "KEY", name: "KeyCorp", logo: "https://logo.clearbit.com/KeyCorp.com", sector: "Financials")
keys = Company.create(ticker: "KEYS", name: "Keysight Technologies", logo: "https://logo.clearbit.com/Keysight.com", sector: "Information Technology")
kmb = Company.create(ticker: "KMB", name: "Kimberly-Clark", logo: "https://logo.clearbit.com/Kimberly-Clark.com", sector: "Consumer Staples")
kim = Company.create(ticker: "KIM", name: "Kimco Realty", logo: "https://logo.clearbit.com/Kimco.com", sector: "Real Estate")
kmi = Company.create(ticker: "KMI", name: "Kinder Morgan", logo: "https://logo.clearbit.com/Kinder.com", sector: "Energy")
klac = Company.create(ticker: "KLAC", name: "KLA Corporation", logo: "https://logo.clearbit.com/KLA.com", sector: "Information Technology")
kss = Company.create(ticker: "KSS", name: "Kohl's Corp.", logo: "https://logo.clearbit.com/Kohls.com", sector: "Consumer Discretionary")
khc = Company.create(ticker: "KHC", name: "Kraft Heinz Co", logo: "https://logo.clearbit.com/Kraft.com", sector: "Consumer Staples")
kr = Company.create(ticker: "KR", name: "Kroger Co.", logo: "https://logo.clearbit.com/Kroger.com", sector: "Consumer Staples")
lb = Company.create(ticker: "LB", name: "L Brands Inc.", logo: "https://logo.clearbit.com/L.com", sector: "Consumer Discretionary")
lhx = Company.create(ticker: "LHX", name: "L3Harris Technologies", logo: "https://logo.clearbit.com/L3Harris.com", sector: "Industrials")
lh = Company.create(ticker: "LH", name: "Laboratory Corp. of America Holding", logo: "https://logo.clearbit.com/Laboratory.com", sector: "Health Care")
lrcx = Company.create(ticker: "LRCX", name: "Lam Research", logo: "https://logo.clearbit.com/Lam.com", sector: "Information Technology")
lw = Company.create(ticker: "LW", name: "Lamb Weston Holdings Inc", logo: "https://logo.clearbit.com/Lamb.com", sector: "Consumer Staples")
lvs = Company.create(ticker: "LVS", name: "Las Vegas Sands", logo: "https://logo.clearbit.com/Las.com", sector: "Consumer Discretionary")
leg = Company.create(ticker: "LEG", name: "Leggett & Platt", logo: "https://logo.clearbit.com/Leggett.com", sector: "Consumer Discretionary")
ldos = Company.create(ticker: "LDOS", name: "Leidos Holdings", logo: "https://logo.clearbit.com/Leidos.com", sector: "Information Technology")
len = Company.create(ticker: "LEN", name: "Lennar Corp.", logo: "https://logo.clearbit.com/Lennar.com", sector: "Consumer Discretionary")
lly = Company.create(ticker: "LLY", name: "Lilly (Eli) & Co.", logo: "https://logo.clearbit.com/Lilly.com", sector: "Health Care")
lnc = Company.create(ticker: "LNC", name: "Lincoln National", logo: "https://logo.clearbit.com/Lincoln.com", sector: "Financials")
lin = Company.create(ticker: "LIN", name: "Linde plc", logo: "https://logo.clearbit.com/Linde.com", sector: "Materials")
lyv = Company.create(ticker: "LYV", name: "Live Nation Entertainment", logo: "https://logo.clearbit.com/Live.com", sector: "Communication Services")
lkq = Company.create(ticker: "LKQ", name: "LKQ Corporation", logo: "https://logo.clearbit.com/LKQ.com", sector: "Consumer Discretionary")
lmt = Company.create(ticker: "LMT", name: "Lockheed Martin Corp.", logo: "https://logo.clearbit.com/Lockheed.com", sector: "Industrials")
l = Company.create(ticker: "L", name: "Loews Corp.", logo: "https://logo.clearbit.com/Loews.com", sector: "Financials")
low = Company.create(ticker: "LOW", name: "Lowe's Cos.", logo: "https://logo.clearbit.com/Lowes.com", sector: "Consumer Discretionary")
lyb = Company.create(ticker: "LYB", name: "LyondellBasell", logo: "https://logo.clearbit.com/LyondellBasell.com", sector: "Materials")
mtb = Company.create(ticker: "MTB", name: "M&T Bank Corp.", logo: "https://logo.clearbit.com/M&T.com", sector: "Financials")
mro = Company.create(ticker: "MRO", name: "Marathon Oil Corp.", logo: "https://logo.clearbit.com/Marathon.com", sector: "Energy")
mpc = Company.create(ticker: "MPC", name: "Marathon Petroleum", logo: "https://logo.clearbit.com/Marathon.com", sector: "Energy")
mktx = Company.create(ticker: "MKTX", name: "MarketAxess", logo: "https://logo.clearbit.com/MarketAxess.com", sector: "Financials")
mar = Company.create(ticker: "MAR", name: "Marriott Int'l.", logo: "https://logo.clearbit.com/Marriott.com", sector: "Consumer Discretionary")
mmc = Company.create(ticker: "MMC", name: "Marsh & McLennan", logo: "https://logo.clearbit.com/Marsh.com", sector: "Financials")
mlm = Company.create(ticker: "MLM", name: "Martin Marietta Materials", logo: "https://logo.clearbit.com/Martin.com", sector: "Materials")
mas = Company.create(ticker: "MAS", name: "Masco Corp.", logo: "https://logo.clearbit.com/Masco.com", sector: "Industrials")
ma = Company.create(ticker: "MA", name: "Mastercard Inc.", logo: "https://logo.clearbit.com/Mastercard.com", sector: "Information Technology")
mkc = Company.create(ticker: "MKC", name: "McCormick & Co.", logo: "https://logo.clearbit.com/McCormick.com", sector: "Consumer Staples")
mxim = Company.create(ticker: "MXIM", name: "Maxim Integrated Products Inc", logo: "https://logo.clearbit.com/Maxim.com", sector: "Information Technology")
mcd = Company.create(ticker: "MCD", name: "McDonald's Corp.", logo: "https://logo.clearbit.com/McDonalds.com", sector: "Consumer Discretionary")
mck = Company.create(ticker: "MCK", name: "McKesson Corp.", logo: "https://logo.clearbit.com/McKesson.com", sector: "Health Care")
mdt = Company.create(ticker: "MDT", name: "Medtronic plc", logo: "https://logo.clearbit.com/Medtronic.com", sector: "Health Care")
mrk = Company.create(ticker: "MRK", name: "Merck & Co.", logo: "https://logo.clearbit.com/Merck.com", sector: "Health Care")
met = Company.create(ticker: "MET", name: "MetLife Inc.", logo: "https://logo.clearbit.com/MetLife.com", sector: "Financials")
mtd = Company.create(ticker: "MTD", name: "Mettler Toledo", logo: "https://logo.clearbit.com/Mettler.com", sector: "Health Care")
mgm = Company.create(ticker: "MGM", name: "MGM Resorts International", logo: "https://logo.clearbit.com/MGM.com", sector: "Consumer Discretionary")
mchp = Company.create(ticker: "MCHP", name: "Microchip Technology", logo: "https://logo.clearbit.com/Microchip.com", sector: "Information Technology")
mu = Company.create(ticker: "MU", name: "Micron Technology", logo: "https://logo.clearbit.com/Micron.com", sector: "Information Technology")
msft = Company.create(ticker: "MSFT", name: "Microsoft Corp.", logo: "https://logo.clearbit.com/Microsoft.com", sector: "Information Technology")
maa = Company.create(ticker: "MAA", name: "Mid-America Apartments", logo: "https://logo.clearbit.com/Mid-America.com", sector: "Real Estate")
mhk = Company.create(ticker: "MHK", name: "Mohawk Industries", logo: "https://logo.clearbit.com/Mohawk.com", sector: "Consumer Discretionary")
tap = Company.create(ticker: "TAP", name: "Molson Coors Brewing Company", logo: "https://logo.clearbit.com/Molson.com", sector: "Consumer Staples")
mdlz = Company.create(ticker: "MDLZ", name: "Mondelez International", logo: "https://logo.clearbit.com/Mondelez.com", sector: "Consumer Staples")
mnst = Company.create(ticker: "MNST", name: "Monster Beverage", logo: "https://logo.clearbit.com/Monster.com", sector: "Consumer Staples")
mco = Company.create(ticker: "MCO", name: "Moody's Corp", logo: "https://logo.clearbit.com/Moodys.com", sector: "Financials")
ms = Company.create(ticker: "MS", name: "Morgan Stanley", logo: "https://logo.clearbit.com/Morgan.com", sector: "Financials")
mos = Company.create(ticker: "MOS", name: "The Mosaic Company", logo: "https://logo.clearbit.com/The.com", sector: "Materials")
msi = Company.create(ticker: "MSI", name: "Motorola Solutions Inc.", logo: "https://logo.clearbit.com/Motorola.com", sector: "Information Technology")
msci = Company.create(ticker: "MSCI", name: "MSCI Inc", logo: "https://logo.clearbit.com/MSCI.com", sector: "Financials")
myl = Company.create(ticker: "MYL", name: "Mylan N.V.", logo: "https://logo.clearbit.com/Mylan.com", sector: "Health Care")
ndaq = Company.create(ticker: "NDAQ", name: "Nasdaq, Inc.", logo: "https://logo.clearbit.com/Nasdaq,.com", sector: "Financials")
nov = Company.create(ticker: "NOV", name: "National Oilwell Varco Inc.", logo: "https://logo.clearbit.com/National.com", sector: "Energy")
ntap = Company.create(ticker: "NTAP", name: "NetApp", logo: "https://logo.clearbit.com/NetApp.com", sector: "Information Technology")
nflx = Company.create(ticker: "NFLX", name: "Netflix Inc.", logo: "https://logo.clearbit.com/Netflix.com", sector: "Communication Services")
nwl = Company.create(ticker: "NWL", name: "Newell Brands", logo: "https://logo.clearbit.com/Newell.com", sector: "Consumer Discretionary")
nem = Company.create(ticker: "NEM", name: "Newmont Corporation", logo: "https://logo.clearbit.com/Newmont.com", sector: "Materials")
nwsa = Company.create(ticker: "NWSA", name: "News Corp. Class A", logo: "https://logo.clearbit.com/News.com", sector: "Communication Services")
nws = Company.create(ticker: "NWS", name: "News Corp. Class B", logo: "https://logo.clearbit.com/News.com", sector: "Communication Services")
nee = Company.create(ticker: "NEE", name: "NextEra Energy", logo: "https://logo.clearbit.com/NextEra.com", sector: "Utilities")
nlsn = Company.create(ticker: "NLSN", name: "Nielsen Holdings", logo: "https://logo.clearbit.com/Nielsen.com", sector: "Industrials")
nke = Company.create(ticker: "NKE", name: "Nike", logo: "https://logo.clearbit.com/Nike.com", sector: "Consumer Discretionary")
ni = Company.create(ticker: "NI", name: "NiSource Inc.", logo: "https://logo.clearbit.com/NiSource.com", sector: "Utilities")
nbl = Company.create(ticker: "NBL", name: "Noble Energy Inc", logo: "https://logo.clearbit.com/Noble.com", sector: "Energy")
nsc = Company.create(ticker: "NSC", name: "Norfolk Southern Corp.", logo: "https://logo.clearbit.com/Norfolk.com", sector: "Industrials")
ntrs = Company.create(ticker: "NTRS", name: "Northern Trust Corp.", logo: "https://logo.clearbit.com/Northern.com", sector: "Financials")
noc = Company.create(ticker: "NOC", name: "Northrop Grumman", logo: "https://logo.clearbit.com/Northrop.com", sector: "Industrials")
nlok = Company.create(ticker: "NLOK", name: "NortonLifeLock", logo: "https://logo.clearbit.com/NortonLifeLock.com", sector: "Information Technology")
nclh = Company.create(ticker: "NCLH", name: "Norwegian Cruise Line Holdings", logo: "https://logo.clearbit.com/Norwegian.com", sector: "Consumer Discretionary")
nrg = Company.create(ticker: "NRG", name: "NRG Energy", logo: "https://logo.clearbit.com/NRG.com", sector: "Utilities")
nue = Company.create(ticker: "NUE", name: "Nucor Corp.", logo: "https://logo.clearbit.com/Nucor.com", sector: "Materials")
nvda = Company.create(ticker: "NVDA", name: "Nvidia Corporation", logo: "https://logo.clearbit.com/Nvidia.com", sector: "Information Technology")
nvr = Company.create(ticker: "NVR", name: "NVR Inc", logo: "https://logo.clearbit.com/NVR.com", sector: "Consumer Discretionary")
orly = Company.create(ticker: "ORLY", name: "O'Reilly Automotive", logo: "https://logo.clearbit.com/OReillyauto.com", sector: "Consumer Discretionary")
oxy = Company.create(ticker: "OXY", name: "Occidental Petroleum", logo: "https://logo.clearbit.com/Occidental.com", sector: "Energy")
odfl = Company.create(ticker: "ODFL", name: "Old Dominion Freight Line", logo: "https://logo.clearbit.com/Old.com", sector: "Industrials")
omc = Company.create(ticker: "OMC", name: "Omnicom Group", logo: "https://logo.clearbit.com/Omnicom.com", sector: "Communication Services")
oke = Company.create(ticker: "OKE", name: "ONEOK", logo: "https://logo.clearbit.com/ONEOK.com", sector: "Energy")
orcl = Company.create(ticker: "ORCL", name: "Oracle Corp.", logo: "https://logo.clearbit.com/Oracle.com", sector: "Information Technology")
otis = Company.create(ticker: "OTIS", name: "Otis Worldwide", logo: "https://logo.clearbit.com/Otis.com", sector: "Industrials")
pcar = Company.create(ticker: "PCAR", name: "PACCAR Inc.", logo: "https://logo.clearbit.com/PACCAR.com", sector: "Industrials")
pkg = Company.create(ticker: "PKG", name: "Packaging Corporation of America", logo: "https://logo.clearbit.com/Packaging.com", sector: "Materials")
ph = Company.create(ticker: "PH", name: "Parker-Hannifin", logo: "https://logo.clearbit.com/Parker-Hannifin.com", sector: "Industrials")
payx = Company.create(ticker: "PAYX", name: "Paychex Inc.", logo: "https://logo.clearbit.com/Paychex.com", sector: "Information Technology")
payc = Company.create(ticker: "PAYC", name: "Paycom", logo: "https://logo.clearbit.com/Paycom.com", sector: "Information Technology")
pypl = Company.create(ticker: "PYPL", name: "PayPal", logo: "https://logo.clearbit.com/PayPal.com", sector: "Information Technology")
pnr = Company.create(ticker: "PNR", name: "Pentair plc", logo: "https://logo.clearbit.com/Pentair.com", sector: "Industrials")
pbct = Company.create(ticker: "PBCT", name: "People's United Financial", logo: "https://logo.clearbit.com/PeoplesFinancial.com", sector: "Financials")
pep = Company.create(ticker: "PEP", name: "PepsiCo Inc.", logo: "https://logo.clearbit.com/PepsiCo.com", sector: "Consumer Staples")
pki = Company.create(ticker: "PKI", name: "PerkinElmer", logo: "https://logo.clearbit.com/PerkinElmer.com", sector: "Health Care")
prgo = Company.create(ticker: "PRGO", name: "Perrigo", logo: "https://logo.clearbit.com/Perrigo.com", sector: "Health Care")
pfe = Company.create(ticker: "PFE", name: "Pfizer Inc.", logo: "https://logo.clearbit.com/Pfizer.com", sector: "Health Care")
pm = Company.create(ticker: "PM", name: "Philip Morris International", logo: "https://logo.clearbit.com/Philip.com", sector: "Consumer Staples")
psx = Company.create(ticker: "PSX", name: "Phillips 66", logo: "https://logo.clearbit.com/Phillips.com", sector: "Energy")
pnw = Company.create(ticker: "PNW", name: "Pinnacle West Capital", logo: "https://logo.clearbit.com/Pinnacle.com", sector: "Utilities")
pxd = Company.create(ticker: "PXD", name: "Pioneer Natural Resources", logo: "https://logo.clearbit.com/Pioneer.com", sector: "Energy")
pnc = Company.create(ticker: "PNC", name: "PNC Financial Services", logo: "https://logo.clearbit.com/PNC.com", sector: "Financials")
ppg = Company.create(ticker: "PPG", name: "PPG Industries", logo: "https://logo.clearbit.com/PPG.com", sector: "Materials")
ppl = Company.create(ticker: "PPL", name: "PPL Corp.", logo: "https://logo.clearbit.com/PPL.com", sector: "Utilities")
pfg = Company.create(ticker: "PFG", name: "Principal Financial Group", logo: "https://logo.clearbit.com/Principal.com", sector: "Financials")
pg = Company.create(ticker: "PG", name: "Procter & Gamble", logo: "https://logo.clearbit.com/Procter.com", sector: "Consumer Staples")
pgr = Company.create(ticker: "PGR", name: "Progressive Corp.", logo: "https://logo.clearbit.com/Progressive.com", sector: "Financials")
pld = Company.create(ticker: "PLD", name: "Prologis", logo: "https://logo.clearbit.com/Prologis.com", sector: "Real Estate")
pru = Company.create(ticker: "PRU", name: "Prudential Financial", logo: "https://logo.clearbit.com/Prudential.com", sector: "Financials")
peg = Company.create(ticker: "PEG", name: "Public Serv. Enterprise Inc.", logo: "https://logo.clearbit.com/Public.com", sector: "Utilities")
psa = Company.create(ticker: "PSA", name: "Public Storage", logo: "https://logo.clearbit.com/Public.com", sector: "Real Estate")
phm = Company.create(ticker: "PHM", name: "PulteGroup", logo: "https://logo.clearbit.com/PulteGroup.com", sector: "Consumer Discretionary")
pvh = Company.create(ticker: "PVH", name: "PVH Corp.", logo: "https://logo.clearbit.com/PVH.com", sector: "Consumer Discretionary")
qrvo = Company.create(ticker: "QRVO", name: "Qorvo", logo: "https://logo.clearbit.com/Qorvo.com", sector: "Information Technology")
pwr = Company.create(ticker: "PWR", name: "Quanta Services Inc.", logo: "https://logo.clearbit.com/Quanta.com", sector: "Industrials")
qcom = Company.create(ticker: "QCOM", name: "QUALCOMM Inc.", logo: "https://logo.clearbit.com/QUALCOMM.com", sector: "Information Technology")
dgx = Company.create(ticker: "DGX", name: "Quest Diagnostics", logo: "https://logo.clearbit.com/Quest.com", sector: "Health Care")
rl = Company.create(ticker: "RL", name: "Ralph Lauren Corporation", logo: "https://logo.clearbit.com/Ralph.com", sector: "Consumer Discretionary")
rjf = Company.create(ticker: "RJF", name: "Raymond James Financial Inc.", logo: "https://logo.clearbit.com/Raymond.com", sector: "Financials")
rtx = Company.create(ticker: "RTX", name: "Raytheon Technologies", logo: "https://logo.clearbit.com/Raytheon.com", sector: "Industrials")
o = Company.create(ticker: "O", name: "Realty Income Corporation", logo: "https://logo.clearbit.com/Realty.com", sector: "Real Estate")
reg = Company.create(ticker: "REG", name: "Regency Centers Corporation", logo: "https://logo.clearbit.com/Regency.com", sector: "Real Estate")
regn = Company.create(ticker: "REGN", name: "Regeneron Pharmaceuticals", logo: "https://logo.clearbit.com/Regeneron.com", sector: "Health Care")
rf = Company.create(ticker: "RF", name: "Regions Financial Corp.", logo: "https://logo.clearbit.com/Regions.com", sector: "Financials")
rsg = Company.create(ticker: "RSG", name: "Republic Services Inc", logo: "https://logo.clearbit.com/Republic.com", sector: "Industrials")
rmd = Company.create(ticker: "RMD", name: "ResMed", logo: "https://logo.clearbit.com/ResMed.com", sector: "Health Care")
rhi = Company.create(ticker: "RHI", name: "Robert Half International", logo: "https://logo.clearbit.com/Robert.com", sector: "Industrials")
rok = Company.create(ticker: "ROK", name: "Rockwell Automation Inc.", logo: "https://logo.clearbit.com/Rockwell.com", sector: "Industrials")
rol = Company.create(ticker: "ROL", name: "Rollins Inc.", logo: "https://logo.clearbit.com/Rollins.com", sector: "Industrials")
rop = Company.create(ticker: "ROP", name: "Roper Technologies", logo: "https://logo.clearbit.com/Roper.com", sector: "Industrials")
rost = Company.create(ticker: "ROST", name: "Ross Stores", logo: "https://logo.clearbit.com/Ross.com", sector: "Consumer Discretionary")
rcl = Company.create(ticker: "RCL", name: "Royal Caribbean Cruises Ltd", logo: "https://logo.clearbit.com/Royal.com", sector: "Consumer Discretionary")
spgi = Company.create(ticker: "SPGI", name: "S&P Global, Inc.", logo: "https://logo.clearbit.com/S&P.com", sector: "Financials")
crm = Company.create(ticker: "CRM", name: "Salesforce.com", logo: "https://logo.clearbit.com/Salesforce.com.com", sector: "Information Technology")
sbac = Company.create(ticker: "SBAC", name: "SBA Communications", logo: "https://logo.clearbit.com/SBA.com", sector: "Real Estate")
slb = Company.create(ticker: "SLB", name: "Schlumberger Ltd.", logo: "https://logo.clearbit.com/Schlumberger.com", sector: "Energy")
stx = Company.create(ticker: "STX", name: "Seagate Technology", logo: "https://logo.clearbit.com/Seagate.com", sector: "Information Technology")
see = Company.create(ticker: "SEE", name: "Sealed Air", logo: "https://logo.clearbit.com/Sealed.com", sector: "Materials")
sre = Company.create(ticker: "SRE", name: "Sempra Energy", logo: "https://logo.clearbit.com/Sempra.com", sector: "Utilities")
now = Company.create(ticker: "NOW", name: "ServiceNow", logo: "https://logo.clearbit.com/ServiceNow.com", sector: "Information Technology")
shw = Company.create(ticker: "SHW", name: "Sherwin-Williams", logo: "https://logo.clearbit.com/Sherwin-Williams.com", sector: "Materials")
spg = Company.create(ticker: "SPG", name: "Simon Property Group Inc", logo: "https://logo.clearbit.com/Simon.com", sector: "Real Estate")
swks = Company.create(ticker: "SWKS", name: "Skyworks Solutions", logo: "https://logo.clearbit.com/Skyworks.com", sector: "Information Technology")
slg = Company.create(ticker: "SLG", name: "SL Green Realty", logo: "https://logo.clearbit.com/SL.com", sector: "Real Estate")
sna = Company.create(ticker: "SNA", name: "Snap-on", logo: "https://logo.clearbit.com/Snap-on.com", sector: "Industrials")
so = Company.create(ticker: "SO", name: "Southern Company", logo: "https://logo.clearbit.com/Southern.com", sector: "Utilities")
luv = Company.create(ticker: "LUV", name: "Southwest Airlines", logo: "https://logo.clearbit.com/Southwest.com", sector: "Industrials")
swk = Company.create(ticker: "SWK", name: "Stanley Black & Decker", logo: "https://logo.clearbit.com/Stanley.com", sector: "Industrials")
sbux = Company.create(ticker: "SBUX", name: "Starbucks Corp.", logo: "https://logo.clearbit.com/Starbucks.com", sector: "Consumer Discretionary")
stt = Company.create(ticker: "STT", name: "State Street Corp.", logo: "https://logo.clearbit.com/State.com", sector: "Financials")
ste = Company.create(ticker: "STE", name: "STERIS plc", logo: "https://logo.clearbit.com/STERIS.com", sector: "Health Care")
syk = Company.create(ticker: "SYK", name: "Stryker Corp.", logo: "https://logo.clearbit.com/Stryker.com", sector: "Health Care")
sivb = Company.create(ticker: "SIVB", name: "SVB Financial", logo: "https://logo.clearbit.com/SVB.com", sector: "Financials")
syf = Company.create(ticker: "SYF", name: "Synchrony Financial", logo: "https://logo.clearbit.com/Synchrony.com", sector: "Financials")
snps = Company.create(ticker: "SNPS", name: "Synopsys Inc.", logo: "https://logo.clearbit.com/Synopsys.com", sector: "Information Technology")
syy = Company.create(ticker: "SYY", name: "Sysco Corp.", logo: "https://logo.clearbit.com/Sysco.com", sector: "Consumer Staples")
tmus = Company.create(ticker: "TMUS", name: "T-Mobile US", logo: "https://logo.clearbit.com/T-Mobile.com", sector: "Communication Services")
trow = Company.create(ticker: "TROW", name: "T. Rowe Price Group", logo: "https://logo.clearbit.com/T..com", sector: "Financials")
ttwo = Company.create(ticker: "TTWO", name: "Take-Two Interactive", logo: "https://logo.clearbit.com/Take-Two.com", sector: "Communication Services")
tpr = Company.create(ticker: "TPR", name: "Tapestry, Inc.", logo: "https://logo.clearbit.com/Tapestry,.com", sector: "Consumer Discretionary")
tgt = Company.create(ticker: "TGT", name: "Target Corp.", logo: "https://logo.clearbit.com/Target.com", sector: "Consumer Discretionary")
tel = Company.create(ticker: "TEL", name: "TE Connectivity Ltd.", logo: "https://logo.clearbit.com/TE.com", sector: "Information Technology")
fti = Company.create(ticker: "FTI", name: "TechnipFMC", logo: "https://logo.clearbit.com/TechnipFMC.com", sector: "Energy")
tfx = Company.create(ticker: "TFX", name: "Teleflex", logo: "https://logo.clearbit.com/Teleflex.com", sector: "Health Care")
txn = Company.create(ticker: "TXN", name: "Texas Instruments", logo: "https://logo.clearbit.com/Texas.com", sector: "Information Technology")
txt = Company.create(ticker: "TXT", name: "Textron Inc.", logo: "https://logo.clearbit.com/Textron.com", sector: "Industrials")
tmo = Company.create(ticker: "TMO", name: "Thermo Fisher Scientific", logo: "https://logo.clearbit.com/Thermo.com", sector: "Health Care")
tif = Company.create(ticker: "TIF", name: "Tiffany & Co.", logo: "https://logo.clearbit.com/Tiffany.com", sector: "Consumer Discretionary")
tjx = Company.create(ticker: "TJX", name: "TJX Companies Inc.", logo: "https://logo.clearbit.com/TJX.com", sector: "Consumer Discretionary")
tsco = Company.create(ticker: "TSCO", name: "Tractor Supply Company", logo: "https://logo.clearbit.com/Tractor.com", sector: "Consumer Discretionary")
tt = Company.create(ticker: "TT", name: "Trane Technologies plc", logo: "https://logo.clearbit.com/Trane.com", sector: "Industrials")
tdg = Company.create(ticker: "TDG", name: "TransDigm Group", logo: "https://logo.clearbit.com/TransDigm.com", sector: "Industrials")
tdy = Company.create(ticker: "TDY", name: "Teledyne Technologies", logo: "https://logo.clearbit.com/Teledyne.com", sector: "Industrials")
trv = Company.create(ticker: "TRV", name: "The Travelers Companies Inc.", logo: "https://logo.clearbit.com/The.com", sector: "Financials")
tfc = Company.create(ticker: "TFC", name: "Truist Financial", logo: "https://logo.clearbit.com/Truist.com", sector: "Financials")
twtr = Company.create(ticker: "TWTR", name: "Twitter, Inc.", logo: "https://logo.clearbit.com/Twitter,.com", sector: "Communication Services")
tsn = Company.create(ticker: "TSN", name: "Tyson Foods", logo: "https://logo.clearbit.com/Tyson.com", sector: "Consumer Staples")
tyl = Company.create(ticker: "TYL", name: "Tyler Technologies", logo: "https://logo.clearbit.com/Tyler.com", sector: "Technology")
udr = Company.create(ticker: "UDR", name: "UDR, Inc.", logo: "https://logo.clearbit.com/UDR,.com", sector: "Real Estate")
ulta = Company.create(ticker: "ULTA", name: "Ulta Beauty", logo: "https://logo.clearbit.com/Ulta.com", sector: "Consumer Discretionary")
usb = Company.create(ticker: "USB", name: "U.S. Bancorp", logo: "https://logo.clearbit.com/U.S..com", sector: "Financials")
uaa = Company.create(ticker: "UAA", name: "Under Armour (Class A)", logo: "https://logo.clearbit.com/Under.com", sector: "Consumer Discretionary")
ua = Company.create(ticker: "UA", name: "Under Armour (Class C)", logo: "https://logo.clearbit.com/Under.com", sector: "Consumer Discretionary")
unp = Company.create(ticker: "UNP", name: "Union Pacific Corp", logo: "https://logo.clearbit.com/Union.com", sector: "Industrials")
ual = Company.create(ticker: "UAL", name: "United Airlines Holdings", logo: "https://logo.clearbit.com/United.com", sector: "Industrials")
unh = Company.create(ticker: "UNH", name: "United Health Group Inc.", logo: "https://logo.clearbit.com/United.com", sector: "Health Care")
ups = Company.create(ticker: "UPS", name: "United Parcel Service", logo: "https://logo.clearbit.com/United.com", sector: "Industrials")
uri = Company.create(ticker: "URI", name: "United Rentals, Inc.", logo: "https://logo.clearbit.com/United.com", sector: "Industrials")
uhs = Company.create(ticker: "UHS", name: "Universal Health Services, Inc.", logo: "https://logo.clearbit.com/Universal.com", sector: "Health Care")
unm = Company.create(ticker: "UNM", name: "Unum Group", logo: "https://logo.clearbit.com/Unum.com", sector: "Financials")
vfc = Company.create(ticker: "VFC", name: "V.F. Corp.", logo: "https://logo.clearbit.com/V.F..com", sector: "Consumer Discretionary")
vlo = Company.create(ticker: "VLO", name: "Valero Energy", logo: "https://logo.clearbit.com/Valero.com", sector: "Energy")
var = Company.create(ticker: "VAR", name: "Varian Medical Systems", logo: "https://logo.clearbit.com/Varian.com", sector: "Health Care")
vtr = Company.create(ticker: "VTR", name: "Ventas Inc", logo: "https://logo.clearbit.com/Ventas.com", sector: "Real Estate")
vrsn = Company.create(ticker: "VRSN", name: "Verisign Inc.", logo: "https://logo.clearbit.com/Verisign.com", sector: "Information Technology")
vrsk = Company.create(ticker: "VRSK", name: "Verisk Analytics", logo: "https://logo.clearbit.com/Verisk.com", sector: "Industrials")
vz = Company.create(ticker: "VZ", name: "Verizon Communications", logo: "https://logo.clearbit.com/Verizon.com", sector: "Communication Services")
vrtx = Company.create(ticker: "VRTX", name: "Vertex Pharmaceuticals Inc", logo: "https://logo.clearbit.com/Vertex.com", sector: "Health Care")
viac = Company.create(ticker: "VIAC", name: "ViacomCBS", logo: "https://logo.clearbit.com/ViacomCBS.com", sector: "Communication Services")
v = Company.create(ticker: "V", name: "Visa Inc.", logo: "https://logo.clearbit.com/Visa.com", sector: "Information Technology")
vno = Company.create(ticker: "VNO", name: "Vornado Realty Trust", logo: "https://logo.clearbit.com/Vornado.com", sector: "Real Estate")
vmc = Company.create(ticker: "VMC", name: "Vulcan Materials", logo: "https://logo.clearbit.com/Vulcan.com", sector: "Materials")
wrb = Company.create(ticker: "WRB", name: "W. R. Berkley Corporation", logo: "https://logo.clearbit.com/W..com", sector: "Financials")
wab = Company.create(ticker: "WAB", name: "Wabtec Corporation", logo: "https://logo.clearbit.com/Wabtec.com", sector: "Industrials")
wmt = Company.create(ticker: "WMT", name: "Walmart", logo: "https://logo.clearbit.com/Walmart.com", sector: "Consumer Staples")
wba = Company.create(ticker: "WBA", name: "Walgreens Boots Alliance", logo: "https://logo.clearbit.com/Walgreens.com", sector: "Consumer Staples")
dis = Company.create(ticker: "DIS", name: "The Walt Disney Company", logo: "https://logo.clearbit.com/The.com", sector: "Communication Services")
wm = Company.create(ticker: "WM", name: "Waste Management Inc.", logo: "https://logo.clearbit.com/Waste.com", sector: "Industrials")
wat = Company.create(ticker: "WAT", name: "Waters Corporation", logo: "https://logo.clearbit.com/Waters.com", sector: "Health Care")
wec = Company.create(ticker: "WEC", name: "WEC Energy Group", logo: "https://logo.clearbit.com/WEC.com", sector: "Utilities")
wfc = Company.create(ticker: "WFC", name: "Wells Fargo", logo: "https://logo.clearbit.com/Wells.com", sector: "Financials")
well = Company.create(ticker: "WELL", name: "Welltower Inc.", logo: "https://logo.clearbit.com/Welltower.com", sector: "Real Estate")
wst = Company.create(ticker: "WST", name: "West Pharmaceutical Services", logo: "https://logo.clearbit.com/West.com", sector: "Health Care")
wdc = Company.create(ticker: "WDC", name: "Western Digital", logo: "https://logo.clearbit.com/Western.com", sector: "Information Technology")
wu = Company.create(ticker: "WU", name: "Western Union Co", logo: "https://logo.clearbit.com/Western.com", sector: "Information Technology")
wrk = Company.create(ticker: "WRK", name: "WestRock", logo: "https://logo.clearbit.com/WestRock.com", sector: "Materials")
wy = Company.create(ticker: "WY", name: "Weyerhaeuser", logo: "https://logo.clearbit.com/Weyerhaeuser.com", sector: "Real Estate")
whr = Company.create(ticker: "WHR", name: "Whirlpool Corp.", logo: "https://logo.clearbit.com/Whirlpool.com", sector: "Consumer Discretionary")
wmb = Company.create(ticker: "WMB", name: "Williams Cos.", logo: "https://logo.clearbit.com/Williams.com", sector: "Energy")
wltw = Company.create(ticker: "WLTW", name: "Willis Towers Watson", logo: "https://logo.clearbit.com/Willis.com", sector: "Financials")
wynn = Company.create(ticker: "WYNN", name: "Wynn Resorts Ltd", logo: "https://logo.clearbit.com/Wynn.com", sector: "Consumer Discretionary")
xel = Company.create(ticker: "XEL", name: "Xcel Energy Inc", logo: "https://logo.clearbit.com/Xcel.com", sector: "Utilities")
xrx = Company.create(ticker: "XRX", name: "Xerox", logo: "https://logo.clearbit.com/Xerox.com", sector: "Information Technology")
xlnx = Company.create(ticker: "XLNX", name: "Xilinx", logo: "https://logo.clearbit.com/Xilinx.com", sector: "Information Technology")
xyl = Company.create(ticker: "XYL", name: "Xylem Inc.", logo: "https://logo.clearbit.com/Xylem.com", sector: "Industrials")
yum = Company.create(ticker: "YUM", name: "Yum! Brands Inc", logo: "https://logo.clearbit.com/Yum!.com", sector: "Consumer Discretionary")
zbra = Company.create(ticker: "ZBRA", name: "Zebra Technologies", logo: "https://logo.clearbit.com/Zebra.com", sector: "Information Technology")
zbh = Company.create(ticker: "ZBH", name: "Zimmer Biomet Holdings", logo: "https://logo.clearbit.com/Zimmer.com", sector: "Health Care")
zion = Company.create(ticker: "ZION", name: "Zions Bancorp", logo: "https://logo.clearbit.com/Zions.com", sector: "Financials")
zts = Company.create(ticker: "ZTS", name: "Zoetis", logo: "https://logo.clearbit.com/Zoetis.com", sector: "Health Care")


#Portfolios

#   Portfolio.destroy_all

portfolio_1 = Portfolio.create(name: "The Port" , starting_value: 17000.00 , user_id: rand(1..6), locked_in_value: 17000.00 , available_cash: 17000.00 )
portfolio_2 = Portfolio.create(name: "Folio" , starting_value: 15000.00 , user_id: rand(1..6), locked_in_value: 15000.00 , available_cash: 15000.00 )
portfolio_3 = Portfolio.create(name: "1st Time Investor" , starting_value: 25000.00 , user_id: rand(1..6), locked_in_value: 25000.00 , available_cash: 25000.00 )
portfolio_4 = Portfolio.create(name: "Tech Stocks", starting_value: 5000.00 , user_id: rand(1..6), locked_in_value: 5000.00 , available_cash: 5000.00)
portfolio_5 = Portfolio.create(name: "Just for Fun", starting_value: 2450.00 , user_id: rand(1..6), locked_in_value: 2450.00 , available_cash: 2450.00 )
portfolio_6 = Portfolio.create(name: "Wall Street Hawk", starting_value: 2304.00 , user_id: rand(1..6), locked_in_value: 2304.00 , available_cash: 2304.00 )
portfolio_7 = Portfolio.create(name: "Seeking Alpha", starting_value: 34500.00 , user_id: rand(1..6), locked_in_value: 34500.00 , available_cash: 34500.00 )
portfolio_8 = Portfolio.create(name: "Better Beta", starting_value: 14000.00 , user_id: rand(1..6), locked_in_value: 14000.00 , available_cash: 14000.00 )
portfolio_9 = Portfolio.create(name: "My Portfolio", starting_value: 12000.00, user_id: rand(1..6), locked_in_value: 12000.00 , available_cash: 12000.00 )
portfolio_10 = Portfolio.create(name: "I'm Rich", starting_value: 18000.00, user_id: rand(1..6), locked_in_value: 18000.00 , available_cash: 18000.00 )
portfolio_11 = Portfolio.create(name: "The Bear", starting_value: 16000.12 , user_id: rand(1..6), locked_in_value: 16000.12 , available_cash: 16000.12)
portfolio_12 = Portfolio.create(name: "Dividender", starting_value: 1800.14 , user_id: rand(1..6), locked_in_value: 1800.14 , available_cash: 1800.14 )
portfolio_13 = Portfolio.create(name: "Mad Money", starting_value: 12000.00 , user_id: rand(1..6), locked_in_value: 12000.00 , available_cash: 12000.00 )
portfolio_14 = Portfolio.create(name: "Market Surfer", starting_value: 50000.00 , user_id: rand(1..6), locked_in_value: 50000.00, available_cash: 50000.00)
portfolio_15 = Portfolio.create(name: "The Bull", starting_value: 17089.00 , user_id: rand(1..6), locked_in_value: 17089.00 , available_cash: 17089.00 )

#Watchlist

Watchlist.create(user_id: 4)

#Transactions

Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 2, value: 341.66, share_price: 170.83, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 3, value: 297.75, share_price: 99.25, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 1, value: 100.83, share_price: 100.83, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 4, value: 1138.2, share_price: 284.55, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 3, value: 665.82, share_price: 221.94, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 2, value: 157.28, share_price: 78.64, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 4, value: 1729.68, share_price: 432.42, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 6, value: 330.24, share_price: 55.04, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 3, value: 434.58, share_price: 144.86, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 3, value: 46.89, share_price: 15.63, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 7, value: 253.54, share_price: 36.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 4, value: 377.48, share_price: 94.37, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 3, value: 882, share_price: 294, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 6, value: 675.9, share_price: 112.65, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 4, value: 148, share_price: 37, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 7, value: 619.22, share_price: 88.46, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 7, value: 1167.25, share_price: 166.75, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 7, value: 764.68, share_price: 109.24, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 4, value: 1289.2, share_price: 322.3, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 1, value: 106.85, share_price: 106.85, company_id: rand(1..500))
Transaction.create(portfolio_id: 37, buy_sell: "buy", quantity: 4, value: 203.08, share_price: 50.77, company_id: rand(1..500))
Transaction.create(portfolio_id: 41, buy_sell: "buy", quantity: 5, value: 458.35, share_price: 91.67, company_id: rand(1..500))
Transaction.create(portfolio_id: 41, buy_sell: "buy", quantity: 1, value: 1515.55, share_price: 1515.55, company_id: rand(1..500))
Transaction.create(portfolio_id: 41, buy_sell: "buy", quantity: 1, value: 41.54, share_price: 41.54, company_id: rand(1..500))
Transaction.create(portfolio_id: 41, buy_sell: "buy", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 41, buy_sell: "buy", quantity: 1, value: 11.91, share_price: 11.91, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 1, value: 87.51, share_price: 87.51, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 1, value: 95.18, share_price: 95.18, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 2, value: 64.24, share_price: 32.12, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 2, value: 518.22, share_price: 259.11, company_id: rand(1..500))
Transaction.create(portfolio_id: 47, buy_sell: "buy", quantity: 2, value: 282.44, share_price: 141.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 47, buy_sell: "buy", quantity: 2, value: 2272.44, share_price: 1136.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 47, buy_sell: "sell", quantity: 2, value: 2272.44, share_price: 1136.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 47, buy_sell: "buy", quantity: 0, value: 0, share_price: 0, company_id: rand(1..500))
Transaction.create(portfolio_id: 47, buy_sell: "buy", quantity: 2, value: 50.56, share_price: 25.28, company_id: rand(1..500))
Transaction.create(portfolio_id: 48, buy_sell: "buy", quantity: 5, value: 593.25, share_price: 118.65, company_id: rand(1..500))
Transaction.create(portfolio_id: 48, buy_sell: "sell", quantity: 3, value: 355.95, share_price: 118.65, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 6, value: 6817.32, share_price: 1136.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "sell", quantity: 2, value: 2272.44, share_price: 1136.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "sell", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "sell", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 49, buy_sell: "buy", quantity: 1, value: 36.22, share_price: 36.22, company_id: rand(1..500))
Transaction.create(portfolio_id: 49, buy_sell: "buy", quantity: -1, value: -322.3, share_price: 322.3, company_id: rand(1..500))
Transaction.create(portfolio_id: 49, buy_sell: "buy", quantity: 0, value: 0, share_price: 0, company_id: rand(1..500))
Transaction.create(portfolio_id: 49, buy_sell: "buy", quantity: 15, value: 396.75, share_price: 26.45, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 2, value: 5923.94, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "sell", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 2, value: 5923.94, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 3, value: 665.819999999999, share_price: 221.94, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 10, value: 4324.2, share_price: 432.42, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 13, value: 2220.79, share_price: 170.83, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 5, value: 1109.7, share_price: 221.94, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 10, value: 29619.6999999999, share_price: 2961.96999999999, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 5, value: 854.15, share_price: 170.83, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "sell", quantity: 4, value: 683.32, share_price: 170.83, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 8, value: 23695.76, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "buy", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 36, buy_sell: "sell", quantity: 1, value: 2961.97, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "buy", quantity: 7, value: 20733.7899999999, share_price: 2961.96999999999, company_id: rand(1..500))
Transaction.create(portfolio_id: 35, buy_sell: "sell", quantity: 4, value: 11847.88, share_price: 2961.97, company_id: rand(1..500))
Transaction.create(portfolio_id: 34, buy_sell: "buy", quantity: 5, value: 393.2, share_price: 78.64, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "buy", quantity: 2, value: 770.62, share_price: 385.31, company_id: rand(1..500))
Transaction.create(portfolio_id: 46, buy_sell: "sell", quantity: 1, value: 385.31, share_price: 385.31, company_id: rand(1..500))
Transaction.create(portfolio_id: 54, buy_sell: "buy", quantity: 3, value: 409.2, share_price: 136.4, company_id: rand(1..500))
Transaction.create(portfolio_id: 54, buy_sell: "sell", quantity: 2, value: 272.8, share_price: 136.4, company_id: rand(1..500))
Transaction.create(portfolio_id: 55, buy_sell: "buy", quantity: 5, value: 593.25, share_price: 118.65, company_id: rand(1..500))


#Watchlist Companies

WatchlistCompany.create(watchlist_id: 4, company_id: 4)
WatchlistCompany.create(watchlist_id: 4, company_id: 5)
WatchlistCompany.create(watchlist_id: 4, company_id: 1)
WatchlistCompany.create(watchlist_id: 4, company_id: 7)
WatchlistCompany.create(watchlist_id: 4, company_id: 9)



